@startuml adapter_extends
skinparam classAttributeIconSize 0

class ShowFile{
  -filename:string
  --
  +__construct(filename: string)
  +showPlain()
  +showHighlight()
}

interface DisplaySourceFile{
  +display()
}

class DisplaySourceFileImpl{
  -show_file : ShowFile
  --
  +__construct(filename: string)
  +display()
}
class Client

DisplaySourceFile <|.up. DisplaySourceFileImpl
DisplaySourceFileImpl --> ShowFile : uses

Client -right-> DisplaySourceFileImpl

note right of DisplaySourceFileImpl
Adapter クラス（委譲型）：
- ShowFile を内部に保持
- DisplaySourceFile を実装
- クライアントは display() を通じて利用
end note

note bottom of ShowFile
ShowFile クラス(継承元) :
- 多数の使用実績あり
- 再利用したいが変更不可
end note

note bottom of DisplaySourceFile
DisplaySourceFile クラス(インターフェース) :
- クライアントにとって簡単なAPI
- 複数のアダプタで使いまわせる
end note
@enduml